Repository AY2021S1-CS2103T-F11-3/tp, pull requests merged in 2020-11, with the labels that each got.

#158 Update DG for v1.3b
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/NegateCommandClassDiagram.puml
  docs/diagrams/RemindMultipleSequenceDiagram.puml
  docs/images/NegateCommandClassDiagram.png
  docs/images/RemindMultipleSequenceDiagram.png
Labels: documentation, type.Task

#240 Branch update Userguide v1.4
  docs/UserGuide.md
Labels: documentation

#182 Update Diagrams in UG and Add Diagrams for FAQ
  docs/UserGuide.md
  docs/images/UserGuideChangeDirectory.PNG
  docs/images/UserGuideCommandPrompt.PNG
  docs/images/UserGuideDoneCommandIndex.PNG
  docs/images/UserGuideDoneCommandSuccess.PNG
  docs/images/UserGuideDoneCommandTicksAdded.PNG
  docs/images/UserGuideHelpCommand.PNG
  docs/images/UserGuideLocateDirectory.PNG
  docs/images/UserGuideReschedule.PNG
  docs/images/UserGuideRescheduleSuccess.PNG
  docs/images/UserGuideUndoneCommandIndex.PNG
  docs/images/UserGuideUndoneCommandSuccess.PNG
  docs/images/UserGuideUndoneCommandTickRemoval.PNG
Labels: documentation

#280 Fix bugs and update RemindCommand error message to handle multiple in…
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
Labels: bug, enhancement

#282 Branch create PPP
  docs/team/printinghelloworld.md
Labels: documentation

#316 Edit editCommandParser
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: enhancement
