Repository AY2021S1-CS2103T-F11-3/tp, pull requests merged in 2020-10, with the labels that each got.

#70 Update README
  README.md
Labels: documentation

#62 Create abstract Task class
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Assignment.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
Labels: enhancement

#16 Add remind command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/Remind.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/testutil/AssignmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
Labels: enhancement

#89 Fix bug causing JsonSerializableAddressBookTest tests to fail
  src/test/data/JsonSerializableAddressBookTest/duplicateAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAssignmentsAddressBook.json
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: bug

#94 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#95 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#119 Edit list to work w assignments
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: enhancement

#127 Update UG for list and find command
  docs/UserGuide.md
Labels: documentation

#128 Update UG for remind and unremind commands
  docs/UserGuide.md
Labels: documentation

#130 Update Storage component in DG
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation

#131 Update model diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#132 Update UG for prioritize and unprioritize commands
  docs/UserGuide.md
Labels: documentation

#134 Update DG with import
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/ImportSequenceDiagram.png
Labels: documentation

#137 Update DG with remind feature implementation
  docs/DeveloperGuide.md
Labels: documentation

#135 Update User Guide with Done and Undone commands
  docs/UserGuide.md
Labels: documentation

#138 Edit Logic component segment
  docs/DeveloperGuide.md
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#143 Update unremind command to work with reminded assignment list
  src/main/java/seedu/address/logic/commands/UnremindCommand.java
  src/test/java/seedu/address/logic/commands/UnremindCommandTest.java
Labels: enhancement

#152 Edit remind command to remind multiple assignments
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandLogic.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
Labels: enhancement

#150 Update remind and unremind description
  docs/UserGuide.md
  docs/images/UserGuideYourReminders.png
Labels: documentation

#144 Auto update list
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
Labels: enhancement, type.Task
